name: Testing cv_copilot

on: push

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install deps
      uses: snok/install-poetry@v1.3.4
      env:
        virtualenvs-create: false
    - name: Run black check
      run: poetry run black --check .
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install deps
      uses: snok/install-poetry@v1.3.4
      env:
        virtualenvs-create: false
    - name: Run flake8 check
      run: poetry run flake8 --count .
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install deps
      uses: snok/install-poetry@v1.3.4
      env:
        virtualenvs-create: false
    - name: Run mypy check
      run: poetry run mypy .
  pytest:
    runs-on: ubuntu-latest
    services:

      cv_copilot-db:
        image: postgres:16-bullseye
        env:
          POSTGRES_PASSWORD: cv_copilot
          POSTGRES_USER: cv_copilot
          POSTGRES_DB: cv_copilot
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
        - 5432:5432
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install deps
      uses: snok/install-poetry@v1.3.4
      env:
        virtualenvs-create: false
    - name: Run pytest check
      run: poetry run pytest -vv --cov="cv_copilot" .
      env:
        CV_COPILOT_HOST: "0.0.0.0"
        CV_COPILOT_DB_HOST: localhost
